apiVersion: pksapi.io/v1beta1
kind: ClusterMetricSink
metadata:
  name: promcloudsink
spec:
  inputs:
  outputs:
  - type: prometheus_client
    listen: ":9978"
    path: "/metrics"
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-metric-sink-service
  namespace: pks-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9273
  selector:
    app: telegraf
  type: ClusterIP
