---
apiVersion: v1
kind: Service
metadata:
  name: metric-sink-service
  namespace: demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9979
  selector:
    app: telegraf-prom-ms-demo
  type: LoadBalancer
