---
apiVersion: v1
kind: Service
metadata:
  name: cluster-metric-sink-service
  namespace: pks-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9223
  selector:
    app: telegraf
  type: ClusterIP
  sessionAffinity: ClientIP
