kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: naomi-rolebinding-default
  namespace: default
subjects:
- kind: User
  name: naomi
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: edit
  apiGroup: rbac.authorization.k8s.io
