FROM openjdk:8-jdk-alpine
VOLUME /tmp
EXPOSE 8080
COPY target/cassandra-demo-0.0.2-SNAPSHOT.jar /app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dserver.servlet.contextPath=/cassandra","-jar","/app.jar"]
