apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv-guestbook
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: csi.vsphere.vmware.com
    fsType: ext4
    volumeAttributes:
      type: vSphere CNS Block Volume
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
